on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: node --version
      - run: npm --version
      - run: node ../../Scrapp.js
